services:
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot-openai
    volumes:
      - ./chatbot/app:/app
    env_file:
      - ./chatbot/.env
    restart: always