from django.db import models
from django.utils import timezone


class Question(models.Model):
    """
    Model to store multiple choice questions generated by AI
    """
    
    # Basic question fields
    question_text = models.TextField(verbose_name="Question text")
    topic = models.CharField(max_length=200, verbose_name="Topic")
    
    # Explanation of the correct answer
    explanation = models.TextField(verbose_name="Explanation")

    class Difficulty(models.TextChoices):
        EASY = 'EASY', 'Fácil'
        MEDIUM = 'MEDIUM', 'Médio'
        HARD = 'HARD', 'Difícil'

    # Add the new field 'difficulty' 
    difficulty = models.CharField(
        max_length=10,
        choices=Difficulty.choices,
        default=Difficulty.MEDIUM,
        verbose_name="Difficulty level"
    )
    
    # Metadata
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    
    # Question status
    is_active = models.BooleanField(default=True, verbose_name="Active")
    
    # AI quality metrics
    confidence_score = models.FloatField(
        default=0.0, 
        verbose_name="Confidence score"
    )
    avg_similarity_score = models.FloatField(
        default=0.0, 
        verbose_name="Average similarity score"
    )
    
    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.topic} - {self.question_text[:50]}..."
    
    def get_correct_option(self):
        """Get the correct option for this question"""
        return self.options.filter(is_correct=True).first()
    
    def get_options_ordered(self):
        """Get all options ordered by creation"""
        return self.options.all().order_by('id')


class Option(models.Model):
    """
    Model to store options for multiple choice questions
    """
    
    # Foreign key to the question
    question = models.ForeignKey(
        Question, 
        on_delete=models.CASCADE, 
        related_name='options',
        verbose_name="Question"
    )
    
    # Option text
    option_text = models.TextField(verbose_name="Option text")
    
    # Indicates if this is the correct answer
    is_correct = models.BooleanField(default=False, verbose_name="Is correct")
    
    # Metadata
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    
    class Meta:
        verbose_name = "Option"
        verbose_name_plural = "Options"
        ordering = ['id']
    
    def __str__(self):
        correct_indicator = " (CORRECT)" if self.is_correct else ""
        return f"{self.question.topic} - {self.option_text[:30]}...{correct_indicator}"


class Program(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Track(models.Model):
    program = models.ForeignKey(Program, on_delete=models.CASCADE, related_name='tracks')
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.program.name} - {self.name}'

class Source(models.Model):
    file_name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.file_name

class Challenge(models.Model):
    class ChallengeStatus(models.TextChoices):
        PENDING = 'PENDING', 'Pendente'
        APPROVED = 'APPROVED', 'Aprovado'

    track = models.ForeignKey('Track', on_delete=models.CASCADE, related_name='challenges')
    title = models.CharField(max_length=255, blank=True, null=True)
    difficulty = models.CharField(
        max_length=10,
        choices=Question.Difficulty.choices,
    )
    status = models.CharField(
        max_length=10,
        choices=ChallengeStatus.choices,
        default=ChallengeStatus.PENDING
    )
    sources = models.ManyToManyField('Source', related_name='challenges')

    def __str__(self):
        return self.title or f"Challenge {self.id}"

class ProblemQuestion(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='problem_questions')
    statement = models.TextField()
    correct_answer = models.DecimalField(max_digits=15, decimal_places=2)
    justification = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.statement[:50] + '...'

class DiscursiveQuestion(models.Model):
    """Stores discursive/textual challenges that do not have numeric answers."""
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='discursive_questions')
    statement = models.TextField()
    answer_text = models.TextField()
    justification = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.statement[:50] + '...'

class MultipleChoiceQuestion(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='multiple_choice_questions')
    statement = models.TextField()
    option_a = models.TextField()
    option_b = models.TextField()
    option_c = models.TextField()
    option_d = models.TextField()
    option_e = models.TextField()
    correct_option = models.CharField(max_length=1)
    justification = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.statement[:50] + '...'