# Generated by Django 5.2.4 on 2025-09-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_challenge_program_source_multiplechoicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado')], default='PENDING', max_length=10),
        ),
    ]
