# Generated by Django 5.2.4 on 2025-10-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_challenge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscursiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('answer_text', models.TextField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discursive_questions', to='questions.challenge')),
            ],
        ),
    ]
