# Generated by Django 5.2.4 on 2025-10-04 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOverallProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trails_accessed', models.PositiveIntegerField(default=0)),
                ('total_access_count', models.PositiveIntegerField(default=0)),
                ('programs_started', models.JSONField(default=list)),
                ('programs_completed', models.JSONField(default=list)),
                ('first_access', models.DateTimeField(blank=True, null=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso Geral',
                'verbose_name_plural': 'Progressos Gerais',
            },
        ),
        migrations.CreateModel(
            name='TrailAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('PROIND', 'PROIND'), ('PRODEPE', 'PRODEPE'), ('PRODEAUTO', 'PRODEAUTO')], max_length=10)),
                ('trail_id', models.CharField(max_length=100)),
                ('trail_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('first_access', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à Trilha',
                'verbose_name_plural': 'Acessos às Trilhas',
                'indexes': [models.Index(fields=['user', 'program'], name='progress_tr_user_id_661197_idx'), models.Index(fields=['user', 'trail_id'], name='progress_tr_user_id_d32b9c_idx'), models.Index(fields=['user', 'last_access'], name='progress_tr_user_id_eb3305_idx')],
                'unique_together': {('user', 'trail_id')},
            },
        ),
        migrations.CreateModel(
            name='UserProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('PROIND', 'PROIND'), ('PRODEPE', 'PRODEPE'), ('PRODEAUTO', 'PRODEAUTO')], max_length=10)),
                ('last_accessed_trail', models.IntegerField(default=0)),
                ('trails_accessed', models.JSONField(default=list)),
                ('total_access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Programa',
                'verbose_name_plural': 'Progressos dos Programas',
                'ordering': ['user', 'program'],
                'indexes': [models.Index(fields=['user', 'program'], name='progress_us_user_id_fca726_idx'), models.Index(fields=['user', 'updated_at'], name='progress_us_user_id_806efb_idx')],
                'unique_together': {('user', 'program')},
            },
        ),
    ]
