# Generated by Django 5.2.4 on 2025-10-13 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_badgedefinition_challengecompletion_userbadge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadgestats',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='badgedefinition',
            name='progress_ba_program_14f2a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='badgedefinition',
            name='progress_ba_difficu_dcfb9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='challengecompletion',
            name='progress_ch_user_id_10009b_idx',
        ),
        migrations.RemoveIndex(
            model_name='challengecompletion',
            name='progress_ch_program_e6513b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailaccess',
            name='progress_tr_user_id_d32b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbadge',
            name='progress_us_user_id_84cd9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbadge',
            name='progress_us_badge_d_57130d_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogramprogress',
            name='progress_us_user_id_fca726_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogramprogress',
            name='progress_us_user_id_806efb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='trailaccess',
            unique_together={('user', 'program', 'trail_number')},
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='first_access',
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='programs_completed',
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='programs_started',
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='total_access_count',
        ),
        migrations.RemoveField(
            model_name='useroverallprogress',
            name='total_trails_accessed',
        ),
        migrations.RemoveField(
            model_name='userprogramprogress',
            name='last_accessed_trail',
        ),
        migrations.RemoveField(
            model_name='userprogramprogress',
            name='total_access_count',
        ),
        migrations.DeleteModel(
            name='UserBadgeStats',
        ),
        migrations.RemoveField(
            model_name='trailaccess',
            name='trail_id',
        ),
    ]
