# Generated by Django 5.2.4 on 2025-10-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_badgedefinition_challengecompletion_userbadge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('PROIND', 'PROIND'), ('PRODEPE', 'PRODEPE'), ('PRODEAUTO', 'PRODEAUTO')], max_length=10)),
                ('track', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('passed', models.BooleanField()),
                ('answers', models.JSONField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teste de Certificado',
                'verbose_name_plural': 'Testes de Certificados',
                'indexes': [models.Index(fields=['user', 'completed_at'], name='progress_ce_user_id_160b3f_idx'), models.Index(fields=['program', 'track'], name='progress_ce_program_637c1b_idx'), models.Index(fields=['passed'], name='progress_ce_passed_c28e4b_idx')],
            },
        ),
    ]
