# Generated by Django 5.2.4 on 2025-10-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_certificatetest'),
        ('progress', '0003_remove_userbadgestats_user_and_more'),
    ]

    operations = [
    ]
