# Generated by Django 5.2.4 on 2025-07-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.AddField(
            model_name='perfil',
            name='areas_of_interest',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_audictor',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
