# Generated by Django 5.2.4 on 2025-07-24 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_perfil_nascimento_remove_perfil_telefone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('linkedin_url', models.URLField(blank=True)),
                ('areas_of_interest', models.CharField(blank=True)),
                ('is_audictor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
